name: Deploy to Server
on:
  push:
    branches: [ server ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH sanity check
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            hostname
            echo "SSH OK"

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd /var/www/tasker-it-backend
            git fetch --all
            git checkout server || git checkout -b server origin/server
            git reset --hard origin/server
            npm ci || npm install
            npx prisma generate
            npx prisma migrate deploy
            pm2 restart tasker-it || pm2 start src/index.js --name tasker-it
            pm2 save
